export const AGENDA_MODULE_OPTIONS = 'AGENDA_MODULE_OPTIONS';
export const AGENDA = 'AGENDA';
export const PARAM_ARGS_METADATA = 'AGENDA_PARAM_ARGS_METADATA';
export const PROCESSOR_METADATA = 'JOB_PROCESSOR_METADATA';
export const JOB_PROCESSORS_METADATA = 'JOB_PROCESSORS_METADATA';
