export const AGENDA_MODULE_OPTIONS = Symbol('AGENDA_MODULE_OPTIONS');
export const AGENDA = Symbol('AGENDA');

export const AGENDA_PARAM_ARGS_METADATA = 'AGENDA_PARAM_ARGS_METADATA';
export const PROCESSORS_DEFINER_METADATA = Symbol(
  'PROCESSORS_DEFINER_METADATA',
);
export const PROCESSOR_METADATA = Symbol('PROCESSOR_METADATA');
export const PROCESSOR_SCHEDULE_METADATA = Symbol(
  'PROCESSOR_SCHEDULE_METADATA',
);
